### ISSUE TITLE
Does this work with AVMATRIX VC42 4-CH?

### ISSUE THREAD

**Issue by zDEFz** [GloriousEggroll/AVMATRIX-VC41-VC42-CAPTURE#2]
I mean, it should, right?

If I get the 4ch card, I should be able to have 4 independent channels.
Also, hows the latency? Would you be able to hold video conferences through the video?
Or even work through it like it was a second pc?

**Comment by GloriousEggroll** [comment]
yes it works on the 4x 1080p port card as well as the 4k loopthrough card
