### ISSUE TITLE
Support for Ubuntu 24.04 and Kernel 6.8 ?

### ISSUE THREAD

**Issue by jniltinho** [GloriousEggroll/AVMATRIX-VC41-VC42-CAPTURE#3]
Support for Ubuntu 24.04 and Kernel 6.8 ?

**Comment by GloriousEggroll** [comment]
should be resolved by https://github.com/GloriousEggroll/AVMATRIX-VC41-VC42-CAPTURE/commit/d9e7e1e7ae6a753a335c0b119dec7e9d18e5daa8

**Comment by jniltinho** [comment]
@GloriousEggroll  :100:

**Comment by jniltinho** [comment]
![image](https://github.com/user-attachments/assets/1d01a601-7673-4c94-ad50-072f9a9a3e21)

**Comment by jniltinho** [comment]
HwsCapture.ko.zst:
Running module version sanity check.
 - Original module
 - Installation
   - Installing to /lib/modules/6.8.0-38-generic/updates/dkms/
depmod...
modprobe: ERROR: could not insert 'HwsCapture': Key was rejected by service
ERROR: Load driver module failed!

**Comment by jniltinho** [comment]
`root@linux-desktop:~/AVMATRIX-VC41-VC42-CAPTURE# ./dkms-install.sh
===================================================
      HWS Linux Driver Installer
===================================================

Checking for required tools ... Done.
Checking for required packages ... Done.
Checking for previous installation ... None
Beginning install, please wait... 
Installing module ... Running dkms ... Creating symlink /var/lib/dkms/HwsCapture.ko/1.0.0.230324/source -> /usr/src/HwsCapture.ko-1.0.0.230324
Warning: I do not know how to handle modules.
Sign command: /usr/bin/kmodsign
Signing key: /var/lib/shim-signed/mok/MOK.priv
Public certificate (MOK): /var/lib/shim-signed/mok/MOK.der

Building module:
Cleaning build area...
make -j16 KERNELRELEASE=6.8.0-38-generic...
Signing module /var/lib/dkms/HwsCapture.ko/1.0.0.230324/build/HwsCapture.ko
Cleaning build area...

HwsCapture.ko.zst:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/6.8.0-38-generic/updates/dkms/
depmod...
modprobe: ERROR: could not insert 'HwsCapture': Key was rejected by service
ERROR: Load driver module failed!

Please check hws_install.log for more details.
If you are experiencing difficulty with this installation
please contact  sales@avmatrix.com
`

**Comment by jniltinho** [comment]
For the build and load of the module to work, I needed to disable SecureBoot in Bios.

**Comment by GloriousEggroll** [comment]
yes its a 3rd party unsigned kernel module, it will never work with secure boot.

**Comment by andremazzone** [comment]
I'd love a bit of help here, since I'm trying to do something similar with a VC12-4K.

I'm on regular Ubuntu 24.04 with kernel 6.8.0-47-generic. CPU is AMD on a B650 board if that's important.

Unlike jniltinho I was able to compile and install the kernel module with secure boot on:

My log looks like this:
```
# ./dkms-install.sh
===================================================
      HWS Linux Driver Installer
===================================================

Checking for required tools ... Done.
Checking for required packages ... Done.
Checking for previous installation ... None
Beginning install, please wait... 
Installing module ... Running dkms ... Creating symlink /var/lib/dkms/HwsUHDX1Capture.ko/1.0.0.230324/source -> /usr/src/HwsUHDX1Capture.ko-1.0.0.230324
Warning: I do not know how to handle modules.
Sign command: /usr/bin/kmodsign
Signing key: /var/lib/shim-signed/mok/MOK.priv
Public certificate (MOK): /var/lib/shim-signed/mok/MOK.der

Building module:
Cleaning build area...
make -j16 KERNELRELEASE=6.8.0-47-generic...
Signing module /var/lib/dkms/HwsUHDX1Capture.ko/1.0.0.230324/build/HwsUHDX1Capture.ko
Cleaning build area...

HwsUHDX1Capture.ko.zst:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/6.8.0-47-generic/updates/dkms/
depmod....

========================================================

Install Successfully!
For more information please check the docs directory or
contact alex.liu@longtimetech.com.

========================================================

```

After a reboot the driver loads and responds to queries from v4l.

```
% v4l2-ctl --list-devices -D
HUHDVideo 1 (HWS):
	/dev/video0

Driver Info:
	Driver name      : HwsUHDX1Capture
	Card type        : HUHDVideo 1
	Bus info         : HWS
	Driver version   : 6.8.12
	Capabilities     : 0x84200001
		Video Capture
		Streaming
		Extended Pix Format
		Device Capabilities
	Device Caps      : 0x04200001
		Video Capture
		Streaming
		Extended Pix Format
```

However, when I try to add the device to OBS, I get a hard crash. It still responds to v4l2-ctl after the crash.

VLC can't connect to it either:
```
% vlc v4l2:///dev/video0
VLC media player 3.0.20 Vetinari (revision 3.0.20-0-g6f0d0ab126b)
[000055b4dc82b5e0] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
[00007e75a4000c90] main input error: Invalid PCR value in ES_OUT_SET_(GROUP_)PCR !
[00007e75a4000c90] main input error: Invalid PCR value in ES_OUT_SET_(GROUP_)PCR !
[00007e75a4000c90] main input error: Invalid PCR value in ES_OUT_SET_(GROUP_)PCR !
[00007e75a4000c90] main input error: Invalid PCR value in ES_OUT_SET_(GROUP_)PCR !
[00007e759c008bc0] main decoder error: buffer deadlock prevented
```

XAWTV fares no better.
```
% xawtv -c /dev/video0 -alsa-cap hw:1,0 
This is xawtv-3.107, running on Linux/x86_64 (6.8.0-47-generic)
xinerama 0: 3840x2160+0+0
ioctl: VIDIOC_ENUMSTD(index=0;id=0x0 [];name="";frameperiod.numerator=0;frameperiod.denominator=0;framelines=0): No data available
Alsa devices: cap: hw:1,0 (/dev/video0), out: default
alsa: Cannot open capture device hw:1,0: No such file or directory
ioctl: VIDIOC_S_FMT(type=VIDEO_CAPTURE;fmt.pix.width=4096;fmt.pix.height=3072;fmt.pix.pixelformat=0x34524742 [BGR4];fmt.pix.field=ANY;fmt.pix.bytesperline=0;fmt.pix.sizeimage=17694720;fmt.pix.colorspace=REC709;fmt.pix.priv=4276996862): Invalid argument
```

The driver still responds to ~v4l2-ctl.


However, when I try to look at it through guvcview, that complains of unsupported ioctls and then v4l2-ctl hangs and won't respond again until I reboot.
```
% guvcview
V4L2_CORE: Unable to find parent usb device.GUVCVIEW: version 2.0.8
GUVCVIEW: couldn't open /home/andre/.config/guvcview2/video0 for read: No such file or directory
V4L2_CORE: (UVCIOC_CTRL_MAP) Error: Inappropriate ioctl for device
V4L2_CORE: (UVCIOC_CTRL_MAP) Error: Inappropriate ioctl for device
V4L2_CORE: (UVCIOC_CTRL_MAP) Error: Inappropriate ioctl for device
V4L2_CORE: (UVCIOC_CTRL_MAP) Error: Inappropriate ioctl for device
V4L2_CORE: (UVCIOC_CTRL_MAP) Error: Inappropriate ioctl for device
V4L2_CORE: (UVCIOC_CTRL_MAP) Error: Inappropriate ioctl for device
V4L2_CORE: (UVCIOC_CTRL_MAP) Error: Inappropriate ioctl for device
V4L2_CORE: (UVCIOC_CTRL_MAP) Error: Inappropriate ioctl for device
V4L2_CORE: (UVCIOC_CTRL_MAP) Error: Inappropriate ioctl for device
Killed

```

Permissions on /dev/video are fine. I can't think of anything else to check.

Any advice would be greatly appreciated.

Thanks in advance!
